# Generated by Django 6.0.6 on 2026-06-16 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subCounty', models.CharField(max_length=100)),
                ('county', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Nyeri', 'Nyeri'), ('Kiambu', 'Kiambu'), ('Nakuru', 'Nakuru'), ('Mombasa', 'Mombasa')], max_length=100)),
                ('terrain', models.CharField(choices=[('Manicured Gardens', 'Manicured Gardens'), ('Indoor Hall', 'Indoor Hall'), ('Rooftop', 'Rooftop'), ('Lakeside', 'Lakeside'), ('Forest', 'Forest')], max_length=100)),
                ('idealFor', models.ManyToManyField(related_name='locations', to='api.eventcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('imageUrl', models.URLField(max_length=500)),
                ('pricePerDay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capacity', models.PositiveIntegerField()),
                ('isLocyfyVerified', models.BooleanField(default=False)),
                ('mlRecommendationScore', models.IntegerField(blank=True, help_text='Percentage 0-100', null=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='venues', to='api.amenity')),
                ('eventLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='api.eventlocation')),
            ],
        ),
    ]
