# Generated by Django 6.0.6 on 2026-06-17 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_venueimage_venuepackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='eventLocation',
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='bookings',
                to='api.eventlocation'),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='venue',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='locations',
                to='api.venue'),
        ),
    ]
